version: '3'
services:
  api:
    build: api/.
    ports:
     - "5000:5000"
    depends_on:
        - redis
        - envoy
    environment:
      Redis: "redis:6379"
      Envoy: "http://envoy:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  envoy:
    build: envoy/.
    ports:
     - "5001:5000"
    depends_on:
        - mssql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=master;User Id=sa;Password=taeTWPukaM8t6lliUals;MultipleActiveResultSets=true"
      ASPNETCORE_ENVIRONMENT: "Development"
  mssql:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      MSSQL_PID: "Developer"
      SA_PASSWORD: "taeTWPukaM8t6lliUals"
      ACCEPT_EULA: "Y"